version: "3.3"

services:
  mysql:
    image: mysql
    environment:
      POSTGRES_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "admin"
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql-vol:
