const yup = require("yup");

exports.createProductSchema = yup.object({
  description: yup.string().required(),
  alias: yup.string(),
  categoryId: yup.number().required(),
  unitInId: yup.number().required(),
  unitOutId: yup.number().required(),
  barcode: yup.string().required(),
  picture: yup.string(),
  itHeadUrdu: yup.string().required(),
  itMinLevel: yup.number(),
  itMaxLevel: yup.number(),
  itRoLevel: yup.number(),
  itRoQty: yup.number(),
  itRate: yup.number(),
  isSerialized: yup.boolean(),
  sTaxRate: yup.number(),
  inUnit: yup.number().required(),
  outUnit: yup.number().required(),
  pType: yup.string(),
  pType1: yup.string(),
  bargen: yup.boolean(),
  brandId: yup.number().required(),
  isStocked: yup.boolean(),
  isFinished: yup.boolean(),
  productTypeId: yup.number().required(),
  intCode: yup.string(),
  openBal: yup.number(),
  hsCode: yup.string(),
});

exports.updateProductSchema = yup.object({
  description: yup.string(),
  alias: yup.string(),
  categoryId: yup.number(),
  unitInId: yup.number(),
  unitOutId: yup.number(),
  barcode: yup.string(),
  picture: yup.string(),
  itHeadUrdu: yup.string(),
  itMinLevel: yup.number(),
  itMaxLevel: yup.number(),
  itRoLevel: yup.number(),
  itRoQty: yup.number(),
  itRate: yup.number(),
  isSerialized: yup.boolean(),
  sTaxRate: yup.number(),
  inUnit: yup.number(),
  outUnit: yup.number(),
  pType: yup.string(),
  pType1: yup.string(),
  bargen: yup.boolean(),
  brandId: yup.number(),
  isStocked: yup.boolean(),
  isFinished: yup.boolean(),
  productTypeId: yup.number(),
  intCode: yup.string(),
  openBal: yup.number(),
  hsCode: yup.string(),
});
